---
title: " Auto-Mpg Data"

Sources: (a) Origin: This dataset was taken from the StatLib library which is maintained at Carnegie Mellon University. The dataset was used in the 1983 American Statistical Association Exposition. (c) Date: July 7, 1993

link : https://archive.ics.uci.edu/ml/datasets/auto+mpg
---

#the data has a mix of quantitative and qualitative (categorical) variables.

#Importing data
```{r}
rm(list = ls())
cars<-read.csv("auto-mpg.csv")
cars
```

#code for descriptive statistics
```{r}
colnames(cars)  #prints variables names of data

# mean, median and standard deviation

mean(cars$weight)
median(cars$weight)
sd(cars$weight)

#highest miles per gallon(mpg) amongst all cars

max(cars$mpg)
min(cars$mpg)

#Which car has the highest and lowest mpg

which.max(cars$mpg)  #prints row number
cars[323,]           #prints whole row of table

which.min(cars$mpg)
cars[29,]


cars[which.max(cars$weight),]
cars[which.min(cars$weight),]

cars[c(23,45,134,329,397),]     #prints given rows

order(cars$weight)  #prints index of rows of columns and sorts them ascendingly

summary(cars)
skewness(cars$displacement)

cars$weight*0.453592
cars$weight_in_kgs<-cars$weight*0.453592      #we transformed weight variable in cars from pounds to kgs and created a new column called weight_in_kgs



```

#Plotting scaatterplots and some more graphs
```{r}
library(ggplot2)
plot(cars$weight, cars$mpg, xlab = "WEIGHT", ylab = "MPG", main = "Scatterplot for Weight vs MPG",col="blue",pch= 21)

boxplot(cars$acceleration, cars$horsepower)

hist(cars$weight, xlab = "WEIGHT", main = "Histogram for Weight", col = "brown" )

```

